steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"

  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - "--image=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--port=8080"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"

substitutions:
  _REGION: asia-east1
  _IMAGE_NAME: yt-relay
  _SERVICE_NAME: yt-relay-dev
