steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        if [ "$BRANCH_NAME" = "master" ]; then
          ENV="prod"
        elif [ "$BRANCH_NAME" = "stag" ]; then
          ENV="staging"
        else
          ENV="dev"
        fi

        echo "ENV=$$ENV" > /workspace/env.sh
        echo "Detected environment: $$ENV"

        gcloud source repos clone configs /workspace/dockerignore/gcr_configs
        cp /workspace/dockerignore/gcr_configs/${_IMAGE_NAME}/$$ENV/config.yml /workspace/configs/config.yml

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"

  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - "--image=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--port=8080"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA"

substitutions:
  _REGION: asia-east1
  _IMAGE_NAME: yt-relay
  _SERVICE_NAME: yt-relay-dev
